### ISSUE TITLE
Always set no_index for t, xt, inc, directories

### ISSUE THREAD

**Issue by thaljef** [rwstauner/Dist-Metadata#12]
As I understand the code now, the metadata is "determined" by merging the default meta with whatever is found in the distribution's META files.  So if the dist author specifies ```no_index``` in the META files, but does not include the t, xt, and inc, directories in that list, then they will be indexed.

However PAUSE *always* ignores those directories (and a few others) regardless of what is in the META, as seen here:

https://github.com/andk/pause/blob/master/lib/PAUSE/dist.pm#L687

Whether or not that should also be the behavior for D::M is not clear to me.

**Comment by xsawyerx** [comment]
@rwstauner so are you in favor of simply adding the directories PAUSE checks?

**Comment by rwstauner** [comment]
Yeah, I think we should probably always exclude the ones PAUSE does:

```
    # skip "t" - libraries in ./t are test libraries!
    # skip "xt" - libraries in ./xt are author test libraries!
    # skip "inc" - libraries in ./inc are usually install libraries
    # skip "local" - somebody shipped his carton setup!
    # skip 'perl5" - somebody shipped her local::lib!
    # skip 'fatlib' 
```

**Comment by rwstauner** [comment]
Sawyer's right, "always use the default dirs" was committed in 2011 (41fc191c4fdc4acd3b1250f0c4ef87d0afd98af5).
The additional dirs have been added.
